# 転置畳み込み(Transposed Convolution)

カーネル$\boldsymbol{K}$と入力値$\boldsymbol{X}$との転置畳み込み(Transposed Convolution; 演算子$\circledast \circledast$で表す)は以下のように表すことができる.ループのストップインデックスはその値を含まない(半開区間$[\mathrm{idx}_{\mathrm{start}}, \mathrm{idx}_{\mathrm{end}})$で表す).  
なお,下式中で$\boldsymbol{\Lambda}$はループ処理を,演算子$+ \gets$は加算代入(+=)を表す.  
また,添字$h$と$w$はそれぞれ画像もしくはカーネルの高さと幅を,$\mathrm{shape}(\cdot)$は指定した次元の長さを表す(たとえば$\boldsymbol{X} \in \mathbb{R}^{2 \times \ 3 \times 4}$において$\mathrm{shape}(\boldsymbol{X})[1]$は$\boldsymbol{X}$の2次元目の長さ3となる.テンソルの次元を表すインデックスは0から始める).

$\boldsymbol{K} \circledast \circledast \boldsymbol{X} := \boldsymbol{f}_{\mathrm{trans \ conv}} (\boldsymbol{X} ;\boldsymbol{K}) \mapsto \boldsymbol{O} \in \mathbb{R}^{(X_h + K_h - 1) \times (X_w + K_w - 1)} = \{$  
$\qquad O_h \gets X_h + K_h - 1$  
$\qquad O_w \gets X_w + K_w - 1$  
$\qquad \boldsymbol{O} \gets \boldsymbol{0}^{O_h \times O_w}$  
$\qquad \boldsymbol{\Lambda}_{i=0}^{\mathrm{shape}(\boldsymbol{X})[0]} \boldsymbol{\Lambda}_{j=0}^{\mathrm{shape}(\boldsymbol{X})[1]} \boldsymbol{O}_{i:i+K_h, j:j+K_w} + \gets X_{i,j} \boldsymbol{K}$  
$ $  
$\qquad \mathrm{return} \ \boldsymbol{O}$  
$\}$

In [ ]:
import numpy as np

In [3]:
def trans_conv(X, K):
    K_h, K_w = K.shape
    X_h, X_w = X.shape
    O_h = X_h + K_h -1
    O_w = X_w + K_w - 1
    O = np.zeros([O_h, O_w])

    for i in range(X_h):
        for j in range(X_w):
            O[i:i + K_h, j:j + K_w] += X[i,j] * K
    
    return O

In [16]:
X = np.array(
    [[0., 1.], 
     [2., 3.]]
)
K = np.array(
    [[0., 1.], 
     [2., 3.]]
)
O = trans_conv(X, K)
print(O)

[[ 0.  0.  1.]
 [ 0.  4.  6.]
 [ 4. 12.  9.]]


今回も参考にしたのは  
Kevin P. Murphy 確率的機械学習:入門編 II: 非線形モデル